http:
  port: 8080

apiEndpoints:
  departments:
    path: /departments
    methods: GET

  department:
    path: /departments/:id
    methods: GET

  apps:
    path: /apps
    methods: GET

  app:
    path: /apps/:id
    methods: GET

  employees:
    path: /employees
    methods: GET

  employee:
    path: /employee/:id
    methods: GET

serviceEndpoints:
  departmentService:
    url: http://departments:3000/api/v1
  appService:
    url: http://apps:3000/api/v1
  employeeService:
    url: http://employees:3000/api/v1

policies:
  - proxy

pipelines:
  default:
    apiEndpoints:
      - departments
      - department

    policies:
      - proxy:
          - action:
              serviceEndpoint: departmentService
              changeOrigin: true

  appsPipeline:
    apiEndpoints:
      - apps
      - app

    policies:
      - proxy:
          - action:
              serviceEndpoint: appService
              changeOrigin: true

  employeesPipeline:
    apiEndpoints:
      - employees
      - employee

    policies:
      - proxy:
          - action:
              serviceEndpoint: employeeService
              changeOrigin: true
